kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rust:bullseye
    commands:
      - rustup component add clippy rustfmt
      - apt-get update -qq
      - apt-get install -qqy llvm-dev libclang-dev clang libspeechd-dev pkg-config libx11-dev libasound2-dev libudev-dev libxcb-xfixes0-dev libwayland-dev libxkbcommon-dev libvulkan-dev libpulse-dev
      - cargo fmt --check
      - cargo test --no-default-features
      - cargo clippy
  - name: release
    image: rust
    commands:
      - cargo publish
    when:
      ref:
        - refs/tags/v*
    environment:
      CARGO_REGISTRY_TOKEN:
        from_secret: cargo_registry_token
  - name: discord notification
    image: appleboy/drone-discord
    when:
      status: [success, failure]
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      tts: true
      message: >
        {{#success build.status}}
          {{repo.name}} build {{build.number}} succeeded: <{{build.link}}>
        {{else}}
          {{repo.name}} build {{build.number}} failed: <{{build.link}}>
        {{/success}}
